server:
  port: 9001
spring:  application:    name: eureka
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:      defaultZone: http://localhost:9001/eureka/